### ISSUE TITLE
Unresolved database class

### ISSUE THREAD

**Issue by rhonyabdullah** [inovex/kotlin-multiplatform-sample#1]
Seems this [Database.Schema](https://github.com/inovex/kotlin-multiplatform-sample/blob/0f93cd93f1c52e48946e82684ea1e5009bec2cbe/app/src/main/java/com/inovex/cpsample/MainActivity.kt#L27) reference issue belongs to [this](https://github.com/square/sqldelight/issues/1300).
I remove this line [org.gradle.parallel=true](https://github.com/inovex/kotlin-multiplatform-sample/blob/1f76c80ca4b0487f2688615ffd4c51c1eb43f183/gradle.properties#L23) and then rebuild the project the Generated class appear but become with another error on `Schema`.

**Comment by janfreymann** [comment]
Hi,

thanks for your interest in the project. Could you please specify the error message? Sometimes, the error message is just in Android Studio, but the gradle build works because IDE support is not yet complete for Kotlin Multiplatform.

I tested again with the following steps:
* clone repository
* use Android Studio 3.5 RC 3 (latest version)
* open folder using "Open existing Android studio project..."
* Build project

Afterwards, the following classes are generated in the build folder:

![grafik](https://user-images.githubusercontent.com/5231877/62779855-96e54c00-bab4-11e9-9a09-805737425f30.png)

**Comment by rhonyabdullah** [comment]
I forget to disable **configureondemand** flag on my `Global Properties` gradle file, although local repository properties disabled it will overriding by global setting, so turning of it will resolve the error.
![image](https://user-images.githubusercontent.com/5601175/62912152-1888f280-bdb1-11e9-90e5-334f110d50c0.png)

Your environment setting is correct also you put the [link](https://github.com/inovex/kotlin-multiplatform-sample/blob/1f76c80ca4b0487f2688615ffd4c51c1eb43f183/gradle.properties#L25), so i think that unresolved reference is coming from my global setting.

**Comment by janfreymann** [comment]
Good to know, I wasn't aware of the global properties. Thanks for the explanation!
